# Generated by Django 4.1.7 on 2023-04-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_address_remove_student_mother_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='english',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='maths',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='science',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='social',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tamil',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
